choice/urls.py
"""
    Copyright 2019 Acacia Shop

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from django.urls import include, path

from .views import (
    HomeView,
    AboutView,
    SuccessView,
    ExamListView,
    ExamDetailView,
    ExamCreateView,
    ExamUpdateView,
    ExamAnswerCreateView,
    ExamAnswerUpdateView,
    DrillUpdateView,
    DrillListView,
    MarkUpdateView,
)
from .views import get_name

app_name = "choice"

exam_extra_patterns = [
    path("", ExamListView.as_view(), name="exam-list",),
    path("<int:pk>/", ExamDetailView.as_view(), name="exam-detail"),
    path("<int:pk>/update", ExamUpdateView.as_view(), name="exam-update"),
    path("<int:pk>/drillupdate", DrillUpdateView.as_view(), name="drill-update"),
    path("<int:pk>/drill", DrillListView.as_view(), name="drill-list"),
    path("create/", ExamCreateView.as_view(), name="exam-create"),
]

drill_extra_patterns = [
    path("<int:pk>/", MarkUpdateView.as_view(), name="mark-update",),
]

exam_answer_extra_patterns = [
    path("", ExamAnswerCreateView.as_view(), name="exam-answer-create"),
    path("<int:pk>/", ExamAnswerUpdateView.as_view(), name="exam-answer-update"),
]
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("test/", get_name, name="test"),
    path("about/", AboutView.as_view(), name="about"),
    path("success/", SuccessView.as_view(), name="success"),
    path("exam/", include(exam_extra_patterns)),
    path("examanswer/", include(exam_answer_extra_patterns)),
    path("drill/", include(drill_extra_patterns)),
]

multiple/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns = [
    path('', include('choice.urls')),
    path('admin/', admin.site.urls),
] + urlpatterns

choice/forms.py
"""
    Copyright 2019 Acacia Shop

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from django import forms
from django.forms import ModelForm, BaseInlineFormSet
from django.forms import inlineformset_factory
from django.utils import timezone
from .models import Exam, Answer, Drill, Publication, Article
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class MultipleQuestionChoiceForm(forms.Form):
    foo_select = forms.ModelMultipleChoiceField(queryset=None)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['foo_select'].queryset = Exam.objects.all()


class ExamForm(forms.Form):
    class Meta:
        model = Exam
        fields = ['title', 'number_of_question']


class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        exclude = ()


AnswerFormSet = inlineformset_factory(Exam, Answer,
                                      form=AnswerForm, extra=1)


class QuestionForm(forms.Form):
    class Meta:
        model = Answer
        fields = ['no', 'sub_no', 'point']


class MyExamForm(ModelForm):
    class Meta:
        model = Exam
        fields = '__all__'

    q_tobemade = forms.IntegerField(
        max_value=60,
        min_value=1,
    )


class DrillInlineFormSet(BaseInlineFormSet):
    def clean(self):
        print("DrillInlineFormSet: passing clean() method.")
        super().clean()
        # example custom validation across forms in the formset
        asof = timezone.now()
        for form in self.forms:
            form.cleaned_data['created'] = asof
            # update the instance value, too.
            form.instance.name = asof


class ExampleFormSetHelper(FormHelper):
    """Return FormHelper from crispy_forms."""
    def __init__(self, *args, **kwargs):
        super(ExampleFormSetHelper, self).__init__(*args, **kwargs)
        self.form_method = 'post'
        self.form_class = 'form-inline'
        self.render_required_fields = True
        self.add_input(Submit("submit", "Save"))


class ArticleForm(ModelForm):
    """ArticleForm class for ManyToManyField sample.

    From Django documentation.
    """

    class Meta:
        model = Article
        fields = ('headline', 'publications')

choice/views.py
"""
    Copyright 2019 Acacia Shop

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""


from django.views.generic import TemplateView, ListView, View
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.edit import CreateView, UpdateView

from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django import forms
from django.forms import ModelForm, inlineformset_factory, Form
from django.db import transaction
from extra_views import CreateWithInlinesView, \
    UpdateWithInlinesView, \
    InlineFormSetFactory
from .models import Exam, Answer, Drill, Mark
from .models import CHOICE_MARK_CHOICES
from .forms import ExampleFormSetHelper
from .forms import ArticleForm
from .forms import AnswerFormSet


class HomeView(TemplateView):
    template_name = "choice/home.html"


class AboutView(TemplateView):
    template_name = "choice/about.html"


class SuccessView(TemplateView):
    template_name = "choice/success.html"


class ExamListView(ListView):
    """ Exam Generic ListView"""
    model = Exam
    paginate_by = 10


class ExamDetailView(DetailView):
    """ Exam Generic DetailView"""
    model = Exam
    

class AnswerInline(InlineFormSetFactory):
    model = Answer
    fields = ['no', 'sub_no', 'point', 'correct']


class ExamCreateView(CreateView):
    """Generic Create View for Exam class."""
    model = Exam
    fields = ['title', 'number_of_question']


class ExamUpdateView(UpdateView):
    """Generic Update View for Exam class."""
    model = Exam
    fields = ['title', 'number_of_question']

    def get_success_url(self):
        """ Return the url when ExamUpdateView succeeds."""
        return reverse('choice:exam-list')


class ExamAnswerCreateView(ExamCreateView):
    """Create View for Exam class with Answer formset."""
    success_url = reverse_lazy('choice:exam-list')
    template_name = 'choice/exam_answer_formset.html'

    def get_context_data(self, **kwargs):
        data = super(ExamAnswerCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['answers'] = AnswerFormSet(self.request.POST)
        else:
            data['answers'] = AnswerFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        answers = context['answers']
        with transaction.atomic():
            self.object = form.save()

            if answers.is_valid():
                answers.instance = self.object
                answers.save()
        return super(ExamAnswerCreateView, self).form_valid(form)


class ExamAnswerUpdateView(ExamUpdateView):
    """Update View for Exam class with Answer formset."""
    success_url = reverse_lazy('choice:exam-list')
    template_name = 'choice/exam_answer_formset.html'

    def get_context_data(self, **kwargs):
        data = super(ExamAnswerUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['answers'] = AnswerFormSet(self.request.POST, instance=self.object)
        else:
            data['answers'] = AnswerFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        answers = context['answers']
        with transaction.atomic():
            self.object = form.save()

            if answers.is_valid():
                answers.instance = self.object
                answers.save()
        return super(ExamAnswerUpdateView, self).form_valid(form)


class DrillUpdateGetView(DetailView):
    """ The Generic class used to render initial form.

    Parent class is Exam.
    """
    model = Exam
    context_object_name = 'exam'
    template_name = 'choice/drill_update.html'

    def get_context_data(self, **kwargs):
        """ Return context for the DetailView as well as DrillFormset and FormHelper.

        Returns:
            context: dictionary of formset and helper
            ::
                {
                    'formset': DrillFormSet,
                    'helper: crispy_forms helper,
                }

        """
        context = super().get_context_data(**kwargs)

        DrillFormSet = inlineformset_factory(
            Exam,
            Drill,
            fields=('description',)
        )
        formset = DrillFormSet(instance=self.object)
        context['formset'] = formset
        helper = ExampleFormSetHelper()
        context['helper'] = helper

        return context


class DrillUpdatePostView(SingleObjectMixin, View):
    """ The generic SingleObjct class providing the post function."""
    model = Exam

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        DrillFormSet = inlineformset_factory(
            Exam,
            Drill,
            fields=('description',)
        )
        formset = DrillFormSet(request.POST, instance=self.object)
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect(
                reverse(
                    'choice:drill-list',
                    kwargs={'pk': self.object.pk}
                )
            )


class DrillUpdateView(View):
    """ Dispatch get and post fuction as requested."""
    def get(self, request, *args, **kwargs):
        view = DrillUpdateGetView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = DrillUpdatePostView.as_view()
        return view(request, *args, **kwargs)


class DrillListView(DetailView):
    model = Exam
    context_object_name = 'exam'
    template_name = 'choice/drill_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Drill.objects.filter(exam=self.object)
        return context


class MarkUpdateGetView(DetailView):
    """ The Generic class used to render initial form.

    Parent class is Drill
    """
    model = Drill
    context_object_name = 'drill'
    template_name = 'choice/mark_update.html'

    def get_context_data(self, **kwargs):
        """ Return context_data as usual as well as MarkFormset.

        Returns:
            context: the dictionary of formset.
            ::
                {
                    'formset': MarkFormSet,
                }

        """
        context = super().get_context_data(**kwargs)
        MarkFormSet = inlineformset_factory(
            Drill,
            Mark,
            fields=('your_choice', 'answer')
        )
        formset = MarkFormSet(instance=self.object)
        context['formset'] = formset

        return context


class MarkUpdatePostView(SingleObjectMixin, View):
    """ The generic SingleObjct class providing post fuction."""
    model = Drill

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        MarkFormSet = inlineformset_factory(
            Drill,
            Mark,
            fields=('your_choice', 'answer')
        )
        formset = MarkFormSet(request.POST, instance=self.object)
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect(
                reverse(
                    'choice:drill-list',
                    kwargs={'pk': self.object.pk}
                )
            )


class MarkUpdateView(View):
    """ Dispatch get and post fuction as requested."""
    def get(self, request, *args, **kwargs):
        view = MarkUpdateGetView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = MarkUpdatePostView.as_view()
        return view(request, *args, **kwargs)


class DrillForm(ModelForm):
    class Meta:
        model = Drill
        fields = ('description',)


ExamDetailFormSet = inlineformset_factory(
    parent_model=Exam,
    model=Drill,
    form=DrillForm,
    extra=1,
    min_num=1,
    validate_min=True,
)


def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ArticleForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required

            newarticle = form.save(commit=False)
            newarticle.headline = 'post'
            newarticle.save()

            form.save()
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('success/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ArticleForm()

    return render(request, 'choice/name.html', {'form': form})

def factorial(n):
    """Return the factorial of n, an exact integer >= 0.

    >>> [factorial(n) for n in range(6)]
    [1, 1, 2, 6, 24, 120]
    >>> factorial(30)
    265252859812191058636308480000000
    >>> factorial(-1)
    Traceback (most recent call last):
        ...
    ValueError: n must be >= 0

    Factorials of floats are OK, but the float must be an exact integer:
    >>> factorial(30.1)
    Traceback (most recent call last):
        ...
    ValueError: n must be exact integer
    >>> factorial(30.0)
    265252859812191058636308480000000

    It must also not be ridiculously large:
    >>> factorial(1e100)
    Traceback (most recent call last):
        ...
    OverflowError: n too large
    """

choice/templates/choice/answer_formset.html
<!-- 
Copyright 2019 Acacia Shop
This file is part of Multiple.
    Multiple is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    Multiple is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with Multiple.  If not, see <https://www.gnu.org/licenses/>.
-->
{% extends "choice/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <div class="container">
      <div class="form-row">
	<div class="col-12">
	  {{ form|crispy }}
	</div>	  
	{% for formset in inlines %}
	  {% crispy formset %}
	{% endfor %}
	<div class="col-12">
	  <input type="submit" class="btn btn-outline-secondary" value="Submit">
	  <a class="btn btn-outline-secondary" href="{% url 'choice:exam-list' %}">Cancel</a>
	</div>
      </div>
    </div>
  </form>
{% endblock %}

choice/templates/choice/base.html
<!-- 
    Copyright 2019 Acacia Shop

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
{% load static %}
<!DOCTYPE html>
<html lang="ja">

  <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>{% block title %}Jumbotron Template · Bootstrap{% endblock title %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/jumbotron/">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <style>
     .bd-placeholder-img {
       font-size: 1.125rem;
       text-anchor: middle;
       -webkit-user-select: none;
       -moz-user-select: none;
       -ms-user-select: none;
       user-select: none;
     }

     @media (min-width: 768px) {
       .bd-placeholder-img-lg {
         font-size: 3.5rem;
       }
     }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'choice/css/choice.css' %}" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href={% url 'choice:home' %}>Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
	<ul class="navbar-nav mr-auto">
	  <li class="nav-item active">
            <a class="nav-link" href="{% url 'choice:exam-list' %}">Exam <span class="sr-only">(current)</span></a>
	  </li>
	  <li class="nav-item">
            <a class="nav-link" href="{% url 'choice:exam-list' %}">Exam 2</a>
	  </li>
	  <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
	  </li>
	  <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'admin:index' %}">Admin index</a>
              <a class="dropdown-item" href="{% url 'admin:logout' %}">Logout</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
	  </li>
	  	  <li class="nav-item">
            <a class="nav-link" href="{% url 'choice:about' %}">about</a>
	  </li>
	</ul>
	<form class="form-inline my-2 my-lg-0">
	  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
	  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	</form>
      </div>
    </nav>

    {% block content %} 
    {% endblock %}
    <footer class="container">
      <p>&copy; Company 2019</p>
    </footer>
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-
		 q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
	    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>

</html>

choice/templates/choice/drill_list.html
<!-- 
    Copyright 2019 Acacia Shop

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
{# -*- coding:utf-8 -*-#}
{% extends "choice/base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-3">
	<p>作成者</p>
      </div>
      <div class="col-9">
	<p>{{ exam.author }}</p>
      </div>
      <div class="col-3">
	<p>作成日</p>
      </div>
      <div class="col-9">
	<p>{{ exam.created_date|date }}</p>
      </div>
      <div class="col-3">
	<p>テスト名</p>
      </div>
      <div class="col-9">
	<p>{{ exam.title }}</p>
      </div>
      {% if object_list %}
      <table class="table table-sm">
	<thead>
	  <tr>
	    <th scope="col">Description</th>
	    <th scope="col">Created</th>
	    <th scope="col">Edit</th>
	  </tr>
	</thead>
	<tbody>
	  {% for drill in object_list %}
	    <tr>
	      <td><a class="btn btn-default" href="#">{{ drill.description}}</a></td>
	      <td>{{ drill.created }}</td>
	      <td><a class="btn btn-outline-secondary" href="#">編集</a>
	      <td><a class="btn btn-outline-secondary" href="#">ドリル追加</a>
	    </tr>
	  {% endfor %}
	</tbody>
      </table>
    {% else %}
      <p>No drill is available.</p>
    {% endif %}
  </div>
{% endblock %}

choice/templates/choice/exam_answer_formset.html
<!--
     Copyright 2019 Acacia Shop

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->
{% extends "choice/base.html" %}
{% load static %}

{% block content %}
    <h2>Exam</h2>
    <hr>
    <div class="col-md-4">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}

            <table class="table">
                {{ answers.management_form }}

                {% for form in answers.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th>{{ field.label|capfirst }}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="{% cycle row1 row2 %} formset_row">
                        {% for field in form.visible_fields %}
                            <td>
                                {# Include the hidden fields in the form #}
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {{ field }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <input type="submit" value="Save"/> <a href="{% url 'choice:exam-list' %}">back to the list</a>
        </form>
    </div>
{% endblock %}

choice/templates/choice/exam_confirm_delete.html
<!-- 
    Copyright 2019 Acacia Shop

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
{# -*- coding:utf-8 -*-#}
{% extends "choice/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12">
	<form action="" method="post">
          {% csrf_token %}
	  <h2 class="text-center">データ削除</h2>
	  {{ object }}
	  <p>このデータを削除します。よろしいですか？</p>
          <input type="submit" class="btn btn-outline-secondary" value="削除" />
          <a class="btn btn-outline-secondary" href="{% url 'choice:exam-detail' object.id %}">戻る</a>
	</form>
      </div>
    </div>
  </div>
{% endblock %}

choice/templates/choice/exam_list.html
<!-- 
    Copyright 2019 Acacia Shop

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
{# -*- coding:utf-8 -*-#}
{% extends "choice/base.html" %}

{% block title %}Exam list{% endblock title%}

{% block content %}
  <main role="main" class="container">

    <div class="row">
      <div class="col-12">
        <div class="float-right">
          <a class="btn btn-outline-secondary" href="{% url 'choice:exam-create' %}">新規</a>
        </div>
      </div>
    </div>
    
    <div class="row" >
      <div class="col-12">
	{% include 'choice/pagination.html' %}
      </div>
    </div>    
    {% if exam_list %}
      <table class="table table-striped">
	<thead>
	  <tr>
	    <th scope="col">pk</th>
	    <th scope="col">Title</th>
	    <th scope="col">Created Date</th>
	    <th scope="col">Edit</th>
	  </tr>
	</thead>
	<tbody>
	  {% for exam in exam_list %}
	    <tr>
	      <th scope="row">{{ exam.id }}</th>
	      <td>{{ exam.title }}</td>
	      <td>{{ exam.created_date }}</td>
	      <td>
		<a class="btn btn-outline-secondary" href="{% url 'choice:exam-update' exam.id %}">Update</a>
		<a class="btn btn-outline-secondary" href="{% url 'choice:drill-update' exam.id %}">ドリル追加</a>
	      </td>
	    </tr>
	  {% endfor %}
	</tbody>
      </table>
    {% else %}
      <p>No exam is available.</p>
    {% endif %}
    <div class="row" >
      <div class="col-12">
	{% include 'choice/pagination.html' %}
      </div>
    </div>    
  </main>
{% endblock content %}